language: ruby
rvm:
- 2.2

matrix:
  allow_failures:
    - rvm: 2.2
  include:
    - python: 3
      env: SPELL=1
    - rvm: 2.2
      env: SPELL=0


before_install:
 - nvm install node

install:
 - |
   if [ "$SPELL" = "1" ]
   then
     pip install codespell --user
   else
     npm install -g csslint
     bundle install
   fi

script:
 - |
   if [ "$SPELL" = "1" ]
   then
     codespell -q3 --skip='.git,*.svg,*.json,*.yml,*.lock,_site'
   else
     bash .travis/cibuild
     csslint _site/css/gallery.css
     csslint _site/css/logo-nav.css
     csslint _site/css/syntax.css
   fi

# branch whitelist, only for GitHub Pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
